version: "3"
services:
    postgres_circle_matcher:
        container_name: postgres_circle_matcher
        image: library/postgres:13.2
        environment:
            POSTGRES_USER: circlematcher
            POSTGRES_PASSWORD: circlematcher
            POSTGRES_DB: circlematcher
        ports:
            -   "5432:5432"
        volumes:
            - postgres_cm_data:/var/lib/postgresql/data
    jaeger:
        container_name: demojaeger
        image: jaegertracing/all-in-one:latest
        ports:
            - "16686:16686"
            - "14268:14268"
            - "5775:5775"
        expose:
            - '16686'
            - '14268'
            - '5775'
#    mongo:
#        image: mongo
#        environment:
#            MONGO_INITDB_ROOT_USERNAME: root
#            MONGO_INITDB_ROOT_PASSWORD: root
#        ports:
#            - "27017:27017"
#        volumes:
#            - mongodb_data:/data/db
volumes:
#    mongodb_data:
    postgres_cm_data: