---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
    app.quarkus.io/commit-id: 6f7ec8bd3ee8a61238c6139c2177f93b97141433
    app.quarkus.io/vcs-url: https://github.com/fbruandrade/circle-matcher.git
    app.quarkus.io/build-timestamp: 2021-01-28 - 13:33:52 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
  labels:
    app.kubernetes.io/name: circle-matcher-native
    app.kubernetes.io/version: 1.0.3
  name: circle-matcher-native
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: circle-matcher-native
    app.kubernetes.io/version: 1.0.3
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
    app.quarkus.io/commit-id: 6f7ec8bd3ee8a61238c6139c2177f93b97141433
    app.quarkus.io/vcs-url: https://github.com/fbruandrade/circle-matcher.git
    app.quarkus.io/build-timestamp: 2021-01-28 - 13:33:52 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
  labels:
    app.kubernetes.io/version: 1.0.3
    app.kubernetes.io/name: circle-matcher-native
  name: circle-matcher-native
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.3
      app.kubernetes.io/name: circle-matcher-native
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
        app.quarkus.io/commit-id: 6f7ec8bd3ee8a61238c6139c2177f93b97141433
        app.quarkus.io/vcs-url: https://github.com/fbruandrade/circle-matcher.git
        app.quarkus.io/build-timestamp: 2021-01-28 - 13:33:52 +0000
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
      labels:
        app.kubernetes.io/version: 1.0.3
        app.kubernetes.io/name: circle-matcher-native
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: QUARKUS_DATASOURCE_JDBC_URL
          value: jdbc:postgresql://192.168.68.100:5432/circlematcher?stringtype=unspecified
        - name: QUARKUS_JAEGER_ENDPOINT
          value: 'http://192.168.68.100:14268/api/traces'
        image: fandrade/circle-matcher:1.0.3
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: circle-matcher
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
