create table circle
(
    id bigint generated by default as identity
        constraint circle_pkey
            primary key,
    circleid uuid,
    created_at timestamp,
    enabled boolean default true,
    isdefault boolean default false,
    match jsonb,
    name varchar(255),
    parameters jsonb,
    parameters_size integer,
    updated_at timestamp,
    workspaceid uuid
);

alter table circle owner to circlematcher;



INSERT INTO public.circle (circleid, created_at, enabled, isdefault, name, updated_at, workspaceid) VALUES ('4987c842-5c41-15eb-ae93-0242ac130007', now(), true, true, 'Default', null, '3612d052-5c41-11eb-ae93-0242ac130002');
INSERT INTO public.circle (circleid, created_at, enabled, isdefault, name, parameters, parameters_size, match, updated_at, workspaceid) VALUES ('2987c842-5c41-11eb-ae93-0242ac130002', now(), true, false, 'Test 2 params', '["temp", "pie"]', 2,'{"and": [{"<": [{"var": "temp"}, 110]}, {"==": [{"var": "pie"}, "apple"]}]}', null, '3612d052-5c41-11eb-ae93-0242ac130002');
INSERT INTO public.circle (circleid, created_at, enabled, isdefault, name, parameters, parameters_size, match, updated_at, workspaceid) VALUES ('54575c6c-5ff8-11eb-ae93-0242ac130002', now(), true, false, 'Test 1 param', '["temp"]', 1,'{"<": [{"var": "temp"}, 110]}', null, '3612d052-5c41-11eb-ae93-0242ac130002');